[versions]
# SDK versions
minSdk = "26" 
compileSdk = "34" 

# Plugins
android-application = "8.2.0"
kotlin-android = "1.9.20"

# Libraries
core-ktx = "1.12.0"
appcompat = "1.6.1"
material = "1.10.0"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-application" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }
